import fs from 'fs'
import os from 'os'
import path from 'path'
import { spawnSync } from 'child_process'
import { fileURLToPath } from 'url'

const PROJECT_ROOT = path.resolve(fileURLToPath(new URL('..', import.meta.url)))
const BIN_DIR = path.join(os.homedir(), '.skilltrace/bin')
const BIN_PATH = path.join(BIN_DIR, 'traceskill')
const LEGACY_BIN_PATH = path.join(os.homedir(), '.local/bin/traceskill')
const MARKER = '# Generated by SkillTrace.'

function main() {
  let command = process.argv[2] || 'install'

  if (command === 'install') {
    install()
  } else if (command === 'uninstall') {
    uninstall()
  } else {
    usage(`Unknown command: ${command}`)
  }
}

function install() {
  fs.mkdirSync(BIN_DIR, { recursive: true })
  fs.writeFileSync(BIN_PATH, wrapperContent(), { mode: 0o755 })
  fs.chmodSync(BIN_PATH, 0o755)

  console.log(`Installed traceskill at ${BIN_PATH}`)
  if (hasGeneratedWrapper(LEGACY_BIN_PATH)) {
    console.log(`Legacy wrapper still exists at ${LEGACY_BIN_PATH}`)
    console.log('Remove it with:')
    console.log('  pnpm traceskill:uninstall')
    console.log('')
  }
  console.log('Try:')
  console.log('  traceskill status')
  console.log('')
  console.log('Register Codex MCP with:')
  console.log('  codex mcp add skilltrace -- traceskill mcp')
  console.log('')
  console.log(`If traceskill is not found, add ${BIN_DIR} to your PATH.`)
}

function uninstall() {
  let removed = false

  for (let binPath of [BIN_PATH, LEGACY_BIN_PATH]) {
    if (!fs.existsSync(binPath)) continue

    let content = fs.readFileSync(binPath, 'utf8')
    if (!content.includes(MARKER)) {
      throw new Error(`${binPath} was not generated by SkillTrace`)
    }

    fs.rmSync(binPath)
    console.log(`Removed ${binPath}`)
    removed = true
  }

  if (!removed) console.log('No generated traceskill command found.')
}

function wrapperContent() {
  let pnpmPath = resolvePnpmPath()

  return `#!/bin/sh
${MARKER}
SKILLTRACE_TARGET_ROOT="\${SKILLTRACE_TARGET_ROOT:-$PWD}" exec ${shellQuote(
    pnpmPath,
  )} --dir ${shellQuote(
    PROJECT_ROOT,
  )} traceskill "$@"
`
}

function resolvePnpmPath() {
  let result = spawnSync('/bin/sh', ['-lc', 'command -v pnpm'], {
    encoding: 'utf8',
  })
  let pnpmPath = result.stdout.trim()

  if (result.status !== 0 || !pnpmPath) {
    throw new Error('pnpm was not found on PATH during traceskill install')
  }

  return pnpmPath
}

function shellQuote(value: string) {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

function hasGeneratedWrapper(binPath: string) {
  return fs.existsSync(binPath) && fs.readFileSync(binPath, 'utf8').includes(MARKER)
}

function usage(message: string): never {
  console.error(message)
  console.error('Usage: pnpm traceskill:install')
  console.error('       pnpm traceskill:uninstall')
  process.exit(1)
}

main()
