import fs from 'fs'
import os from 'os'
import path from 'path'
import { fileURLToPath } from 'url'

const PROJECT_ROOT = path.resolve(fileURLToPath(new URL('..', import.meta.url)))
const BIN_DIR = path.join(os.homedir(), '.skilltrace/bin')
const PRIMARY_BIN_PATH = path.join(BIN_DIR, 'skilltrace-dev')
const ALIAS_BIN_PATH = path.join(BIN_DIR, 'traceskill-dev')
const OLD_BIN_PATH = path.join(BIN_DIR, 'traceskill')
const LEGACY_BIN_PATH = path.join(os.homedir(), '.local/bin/traceskill')
const MARKER = '# Generated by SkillTrace.'
const DEV_SERVER = 'http://localhost:5777'
const DEV_PORT = '5777'

function main() {
  let command = process.argv[2] || 'install'

  if (command === 'install') {
    install()
  } else if (command === 'uninstall') {
    uninstall()
  } else {
    usage(`Unknown command: ${command}`)
  }
}

function install() {
  fs.mkdirSync(BIN_DIR, { recursive: true })
  for (let binPath of [PRIMARY_BIN_PATH, ALIAS_BIN_PATH]) {
    fs.writeFileSync(binPath, wrapperContent(), { mode: 0o755 })
    fs.chmodSync(binPath, 0o755)
  }

  console.log(`Installed skilltrace-dev at ${PRIMARY_BIN_PATH}`)
  console.log(`Installed traceskill-dev alias at ${ALIAS_BIN_PATH}`)
  cleanupOldWrapper(OLD_BIN_PATH)
  cleanupOldWrapper(LEGACY_BIN_PATH)
  console.log('Try:')
  console.log('  skilltrace-dev status')
  console.log('')
  console.log('Register Codex MCP with:')
  console.log('  codex mcp add skilltrace -- skilltrace-dev mcp')
  console.log('  claude mcp add skilltrace --scope user -- skilltrace-dev mcp')
  console.log('  gemini mcp add skilltrace skilltrace-dev mcp --scope user ')
  console.log('')
  console.log(`If skilltrace-dev is not found, add ${BIN_DIR} to your PATH.`)
  console.log(`Development server defaults to ${DEV_SERVER}.`)
}

function uninstall() {
  let removed = false

  for (let binPath of [
    PRIMARY_BIN_PATH,
    ALIAS_BIN_PATH,
    OLD_BIN_PATH,
    LEGACY_BIN_PATH,
  ]) {
    if (!fs.existsSync(binPath)) continue

    let content = fs.readFileSync(binPath, 'utf8')
    if (!content.includes(MARKER)) {
      throw new Error(`${binPath} was not generated by SkillTrace`)
    }

    fs.rmSync(binPath)
    console.log(`Removed ${binPath}`)
    removed = true
  }

  if (!removed) console.log('No generated skilltrace-dev command found.')
}

function wrapperContent() {
  let nodePath = process.execPath
  let tsxLoaderPath = path.join(
    PROJECT_ROOT,
    'node_modules/tsx/dist/loader.mjs',
  )
  let traceskillPath = path.join(PROJECT_ROOT, 'scripts/traceskill.ts')

  return `#!/bin/sh
${MARKER}
if [ -z "\${SKILLTRACE_TARGET_ROOT:-}" ]; then
  SKILLTRACE_TARGET_ROOT="$(pwd -P 2>/dev/null || printf '%s' "\${PWD:-}")"
fi
cd ${shellQuote(PROJECT_ROOT)} || exit 1
export SKILLTRACE_TARGET_ROOT
SKILLTRACE_DEV="\${SKILLTRACE_DEV:-1}" \\
SKILLTRACE_SERVER="\${SKILLTRACE_SERVER:-${DEV_SERVER}}" \\
PORT="\${PORT:-${DEV_PORT}}" \\
exec ${shellQuote(nodePath)} --import ${shellQuote(tsxLoaderPath)} ${shellQuote(
    traceskillPath,
  )} "$@"
`
}

function shellQuote(value: string) {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

function hasGeneratedWrapper(binPath: string) {
  return (
    fs.existsSync(binPath) && fs.readFileSync(binPath, 'utf8').includes(MARKER)
  )
}

function cleanupOldWrapper(binPath: string) {
  if (!fs.existsSync(binPath)) return
  if (!hasGeneratedWrapper(binPath)) {
    console.log(`Preserved non-SkillTrace wrapper at ${binPath}`)
    return
  }

  fs.rmSync(binPath)
  console.log(`Removed old generated wrapper at ${binPath}`)
}

function usage(message: string): never {
  console.error(message)
  console.error('Usage: pnpm traceskill:install')
  console.error('       pnpm traceskill:uninstall')
  process.exit(1)
}

main()
