import path from 'path'
import fs from 'fs'
import os from 'os'
import { spawn, spawnSync } from 'child_process'
import { createInterface } from 'readline/promises'
import { fileURLToPath } from 'url'
import {
  assessInstrumentation,
  ejectExistingInstructions,
  ejectInstructions,
  injectInstructions,
  instructionInjectionStatus,
} from './lib/instruction-injection'
import {
  detectInstructionSurfaces,
  instructionProfileExpectation,
  instructionProfileReady,
  selectInstructionProfile,
  type InstructionProfile,
  type InstructionProfileOption,
  type InstructionSurfaceReport,
} from './lib/instruction-profile'
import {
  getJson as requestJson,
  postJson as sendJson,
} from './lib/skilltrace-http'
import { captureGitSnapshot } from './lib/skilltrace-git-snapshot'
import {
  DAEMON_DIR,
  DAEMON_LOG_PATH,
  readDaemonState,
  removeDaemonState,
  type DaemonState,
  writeDaemonState,
} from './lib/skilltrace-daemon-state'
import {
  cleanupSharedProbeWorkers,
  killProcessGroup,
  killProcessTree,
  processAlive,
  processOwnsServer,
  sharedProbeWorkers,
  stopProcessTree,
  waitForExit,
} from './lib/skilltrace-process'
import {
  expectedMcpServerCommand,
  manageMcpInstall,
  manageMcpUninstall,
  printMcpStatus,
} from './lib/skilltrace-mcp-management'

const DEFAULT_SERVER = 'http://localhost:7555'
const PROJECT_ROOT = path.resolve(fileURLToPath(new URL('..', import.meta.url)))
const ENTRY_DIR = path.dirname(fileURLToPath(import.meta.url))
const DIST_MODE = path.basename(ENTRY_DIR) === 'dist'
const TSX_LOADER_PATH = path.join(PROJECT_ROOT, 'node_modules', 'tsx', 'dist', 'loader.mjs')
const RUNTIME_ENV_IMPORT_PATH = DIST_MODE
  ? path.join(ENTRY_DIR, 'skilltrace-runtime-env.js')
  : path.join(PROJECT_ROOT, 'scripts/lib/skilltrace-runtime-env.js')
const PACKAGE_JSON_PATH = path.join(PROJECT_ROOT, 'package.json')
const DEV_MODE = process.env.SKILLTRACE_DEV === '1'

async function main() {
  let [command, ...args] = process.argv.slice(2)
  if (command === '--version') {
    console.log(skilltraceVersion())
    return
  }

  if (!(command === 'mcp' && args[0] === 'serve')) warnIfDevWrapperStale()

  if (command === 'start') {
    await start(args)
  } else if (command === 'end' || command === 'stop') {
    await end(args)
  } else if (command === 'status') {
    await status(args)
  } else if (command === 'diagnostics') {
    await diagnostics(args)
  } else if (command === 'serve') {
    runServe()
  } else if (command === 'daemon') {
    await daemon(args)
  } else if (command === 'mcp') {
    await mcp(args)
  } else {
    usage(command ? `Unknown command: ${command}` : 'Missing command')
  }
}

function warnIfDevWrapperStale() {
  if (!DEV_MODE) return

  let warnings = devWrapperWarnings()
  for (let warning of warnings) {
    console.warn(`Warning: ${warning}`)
  }
  if (warnings.length > 0) {
    console.warn('Run `pnpm skilltrace:install` from the SkillTrace checkout.')
  }
}

function devWrapperWarnings() {
  let binDir = path.join(os.homedir(), '.skilltrace/bin')
  let warnings: string[] = []

  let name = 'skilltrace-dev'
  let filePath = path.join(binDir, name)
  if (!fs.existsSync(filePath)) {
    warnings.push(`${name} is missing from ${binDir}.`)
    return warnings
  }

  let content = fs.readFileSync(filePath, 'utf8')
  if (!isCurrentDevWrapper(content)) {
    warnings.push(`${name} looks stale.`)
  }

  return warnings
}

function isCurrentDevWrapper(content: string) {
  return (
    content.includes('# Generated by SkillTrace.') &&
    content.includes('SKILLTRACE_TARGET_ROOT="$(pwd -P') &&
    content.includes(PROJECT_ROOT) &&
    content.includes('scripts/traceskill.ts')
  )
}

async function start(args: string[]) {
  let options = parseArgs(args)
  let targetRoot = path.resolve(options.target || defaultTargetRoot())
  let server = options.server || process.env.SKILLTRACE_SERVER || DEFAULT_SERVER
  let probe = passiveProbeSupport()
  let sharedProbe = sharedProbeStatus(server)
  let traceMode = traceModeForStart(options)
  let shouldInjectInstructions = traceMode !== 'passive_only'
  let instructionSurfaces = detectInstructionSurfaces(targetRoot)
  let instructionProfile = selectInstructionProfile(
    options.instructionProfile,
    instructionSurfaces,
  )
  assertTraceTarget(targetRoot, instructionProfile.selected, instructionSurfaces)
  let instrumentation = withPassiveProbeWarning(
    assessInstrumentation(
      targetRoot,
      shouldInjectInstructions,
      instructionProfile.selected,
    ),
    probe,
  )
  let active = await getJson(server, '/api/sessions/status')
  if (active.session) {
    printActiveSessionRefusal(server, active.session)
    process.exit(1)
  }

  let useSharedProbe = sharedProbe.available
  if (probe.supported && probe.platform === 'darwin' && !useSharedProbe) primeSudo()
  cleanupTargetInjection(targetRoot)
  let gitSnapshot = captureGitSnapshot(targetRoot)
  let executionEnvironment = runExecutionEnvironment(probe, sharedProbe)

  let result = await postJson(server, '/api/sessions/start', {
    target_root: targetRoot,
    instrumentation,
    note: options.note,
    trace_mode: traceMode,
    git_snapshot: gitSnapshot,
    instruction_surfaces: instructionSurfaces,
    instruction_profile: instructionProfile,
    execution_environment: executionEnvironment,
  })
  printInstrumentationWarning(instrumentation, shouldInjectInstructions)
  let injection = shouldInjectInstructions
    ? injectInstructions(targetRoot, result.session.run_id, {
      traceMode,
      instructionProfile: instructionProfile.selected,
    })
    : null
  if (injection) {
    printInjectionResult('Instruction injection', injection)
    await postSessionEvent(server, result.session.run_id, 'instruction_injection_started', {
      ...injection,
      target_root: targetRoot,
    })
  }
  if (sharedProbe.requested && !sharedProbe.available) {
    printSharedProbeFallbackWarning(sharedProbe)
    await postSessionEvent(server, result.session.run_id, 'trace_probe_shared_unavailable', {
      reason: sharedProbe.reason,
      target_root: targetRoot,
    })
  }
  let worker: ProbeWorker | null = null
  let workerFailure: string | undefined
  let canStartRunProbe = !useSharedProbe && probe.supported && !sharedProbe.blocksRunProbe
  if (canStartRunProbe) {
    let candidate = startProbeWorker({
      runId: result.session.run_id,
      targetRoot,
      server,
      debug: options.debugProbe,
    })
    if (await waitForProbeStartup(candidate.pid)) {
      worker = candidate
    } else {
      workerFailure = `probe worker exited during startup; check ${candidate.logPath}`
    }
  }

  if (useSharedProbe && sharedProbe.state?.shared_probe_pid) {
    await postJson(server, '/api/sessions/probe', {
      run_id: result.session.run_id,
      probe_pid: sharedProbe.state.shared_probe_pid,
      probe_log_path: sharedProbe.state.shared_probe_log_path,
      probe_kind: 'shared',
    })
    await postSessionEvent(server, result.session.run_id, 'trace_probe_shared_attached', {
      probe_pid: sharedProbe.state.shared_probe_pid,
      probe_log_path: sharedProbe.state.shared_probe_log_path,
      target_root: targetRoot,
    })
  } else if (worker) {
    await postJson(server, '/api/sessions/probe', {
      run_id: result.session.run_id,
      probe_pid: worker.pid,
      probe_log_path: worker.logPath,
      probe_kind: 'run',
    })
  } else {
    let reason = workerFailure ?? sharedProbe.reason ?? probe.reason
    printProbeUnavailableWarning(reason)
    await postSessionEvent(server, result.session.run_id, 'trace_probe_unavailable', {
      platform: probe.platform,
      reason,
      target_root: targetRoot,
    })
  }

  printSession('Started SkillTrace session', server, {
    ...result.session,
    probe_pid: sharedProbe.available
      ? sharedProbe.state?.shared_probe_pid
      : worker?.pid,
    probe_log_path: sharedProbe.available
      ? sharedProbe.state?.shared_probe_log_path
      : worker?.logPath,
    probe_kind: sharedProbe.available ? 'shared' : worker ? 'run' : undefined,
  })
}

async function end(args: string[]) {
  let options = parseArgs(args)
  let server = options.server || process.env.SKILLTRACE_SERVER || DEFAULT_SERVER

  if (options.discard) {
    let active = await getJson(server, '/api/sessions/status')
    if (!active.session) {
      console.log('No active SkillTrace session to discard.')
      return
    }

    if (!options.yes && !(await confirmDiscard(active.session))) {
      console.log('Discard cancelled.')
      return
    }
  }

  await cleanupActiveInjection(server)

  let result = await postJson(server, '/api/sessions/end', {
    discard: options.discard === true,
  })

  if (result.session) {
    if (options.discard) {
      printDiscardedSession(result.session)
    } else {
      printSession('Ended SkillTrace session', server, result.session)
    }
  } else {
    console.log(options.discard
      ? 'No active SkillTrace session to discard.'
      : 'No active SkillTrace session.')
  }
}

async function status(args: string[]) {
  let options = parseArgs(args)
  let server = options.server || process.env.SKILLTRACE_SERVER || DEFAULT_SERVER
  let result = await getJson(server, '/api/sessions/status')

  if (result.session) {
    printSession('Active SkillTrace session', server, result.session)
  } else {
    console.log('No active SkillTrace session.')
  }
}

async function diagnostics(args: string[]) {
  let options = parseArgs(args)
  let server = options.server || process.env.SKILLTRACE_SERVER || DEFAULT_SERVER
  let result = await getJson(server, '/api/diagnostics')
  let diagnostics = result.diagnostics

  if (options.verbose) {
    printDiagnosticsVerbose(diagnostics)
  } else {
    printDiagnosticsCompact(diagnostics)
  }
}

async function daemon(args: string[]) {
  let [command, ...rest] = args

  if (command === 'start') {
    await daemonStart(rest)
  } else if (command === 'stop') {
    await daemonStop(rest)
  } else if (command === 'status') {
    await daemonStatus(rest)
  } else if (command === 'logs') {
    daemonLogs(rest)
  } else {
    usage(command ? `Unknown daemon command: ${command}` : 'Missing daemon command')
  }
}

async function mcp(args: string[]) {
  let [command, ...rest] = args

  if (!command) {
    mcpUsage()
  } else if (command === 'serve') {
    runScript('scripts/skilltrace-mcp.ts')
  } else if (command === 'install') {
    await mcpInstall(rest)
  } else if (command === 'uninstall') {
    await mcpUninstall(rest)
  } else if (command === 'status') {
    await mcpStatus(rest)
  } else {
    usage(`Unknown mcp command: ${command}`)
  }
}

async function mcpInstall(args: string[]) {
  let options = parseArgs(args)
  assertMcpAgent(options.agent)
  manageMcpInstall({
    agent: options.agent,
    devMode: DEV_MODE,
  })
}

async function mcpUninstall(args: string[]) {
  let options = parseArgs(args)
  assertMcpAgent(options.agent)
  manageMcpUninstall({
    agent: options.agent,
    devMode: DEV_MODE,
  })
}

async function mcpStatus(args: string[]) {
  let options = parseArgs(args)
  assertMcpAgent(options.agent)
  printMcpStatus({
    agent: options.agent,
    devMode: DEV_MODE,
    verbose: options.verbose,
  })
}

function assertMcpAgent(agent?: string) {
  if (!agent || ['codex', 'claude', 'gemini'].includes(agent)) return
  usage(`Unknown MCP agent: ${agent}`)
}

async function daemonStart(args: string[]) {
  let options = parseArgs(args)
  let server = options.server || process.env.SKILLTRACE_SERVER || DEFAULT_SERVER
  let bindHost = process.env.HOST || '127.0.0.1'
  let port = process.env.PORT || new URL(server).port || '7555'
  let status = await getDaemonStatus(server)
  let requestSharedProbe = sharedProbeRequested(options)

  if (status.alive) {
    if (status.state) {
      console.log('SkillTrace daemon is already running.')
      printBindChangeHint(status.state, bindHost, port)
      printSharedProbeChangeHint(status.state, requestSharedProbe)
    } else {
      console.log('A SkillTrace server is already responding.')
    }
    printDaemonStatus(status)
    return
  }

  let sharedProbe = await prepareSharedProbe(requestSharedProbe, server)
  fs.mkdirSync(path.dirname(DAEMON_LOG_PATH), { recursive: true })
  let logFd = fs.openSync(DAEMON_LOG_PATH, 'a')
  let child = spawn(serveCommand(), serveArgs(), {
    cwd: PROJECT_ROOT,
    detached: true,
    stdio: ['ignore', logFd, logFd],
    env: {
      ...process.env,
      SKILLTRACE_DAEMON: '1',
    },
  })

  child.unref()
  fs.closeSync(logFd)

  if (typeof child.pid !== 'number') {
    throw new Error('Failed to start SkillTrace daemon')
  }

  if (sharedProbe.requested && process.platform === 'darwin' && !sharedProbe.warning) {
    let candidate = startSharedProbeWorker({
      server,
      debug: options.debugProbe,
    })
    if (await waitForProbeStartup(candidate.pid)) {
      sharedProbe.worker = candidate
    } else {
      sharedProbe.warning = `shared probe exited during startup; check ${candidate.logPath}`
      sharedProbe.blocksRunProbe = true
      killProcessGroup(candidate.pid, 'SIGTERM')
      killProcessTree(candidate.pid, 'SIGTERM')
      await waitForExit(candidate.pid)
    }
  }

  let state = {
    pid: child.pid,
    server,
    bind_host: bindHost,
    bind_port: port,
    ui_urls: displayUrls(bindHost, port),
    log_path: DAEMON_LOG_PATH,
    started_at: new Date().toISOString(),
    shared_probe_requested: sharedProbe.requested,
    shared_probe_pid: sharedProbe.worker?.pid,
    shared_probe_log_path: sharedProbe.worker?.logPath,
    shared_probe_platform: sharedProbe.worker ? process.platform : undefined,
    shared_probe_warning: sharedProbe.warning,
    shared_probe_blocks_run_probe: sharedProbe.blocksRunProbe,
  }

  writeDaemonState(state)

  console.log('Started experimental SkillTrace daemon.')
  console.log(`  pid: ${state.pid}`)
  console.log(`  server: ${state.server}`)
  console.log(`  bind: ${state.bind_host}:${port}`)
  printDisplayUrls(state.ui_urls)
  printSharedProbeDaemonState(state)
  console.log(`  log: ${state.log_path}`)

  let startup = await waitForDaemon(child.pid, server)
  if (startup.ready) {
    console.log('  health: ok')
  } else {
    await stopStartedDaemon(state)
    console.log('  health: not ready yet')
    if (startup.health?.ok) {
      console.log(`  warning: ${server} is responding from pid ${startup.health.pid ?? 'unknown'}, not ${child.pid}`)
    }
    console.log('  check: skilltrace daemon logs')
  }
}

async function daemonStop(args: string[]) {
  let options = parseArgs(args)
  let state = readDaemonState()
  let server = options.server || state?.server || process.env.SKILLTRACE_SERVER || DEFAULT_SERVER

  if (!state) {
    await cleanupSharedProbeWorkers(server)
    console.log('No SkillTrace daemon state found.')
    if (await isServerAlive(server)) console.log(`A server is responding at ${server}.`)
    return
  }

  await cleanupActiveInjection(server)
  await endServerSession(server)
  if (state.shared_probe_pid) {
    await stopProcessTree(state.shared_probe_pid)
  }
  await cleanupSharedProbeWorkers(server)
  if (processAlive(state.pid)) {
    killProcessGroup(state.pid, 'SIGTERM')
    killProcessTree(state.pid, 'SIGTERM')
    await waitForExit(state.pid)
  }
  if (processAlive(state.pid)) {
    killProcessGroup(state.pid, 'SIGKILL')
    killProcessTree(state.pid, 'SIGKILL')
    await waitForExit(state.pid)
  }

  removeDaemonState()
  if (await isServerAlive(server)) {
    console.log('SkillTrace daemon state was removed, but a server is still responding.')
  } else {
    console.log('Stopped SkillTrace daemon.')
  }
}

async function stopStartedDaemon(state: DaemonState) {
  if (state.shared_probe_pid) {
    await stopProcessTree(state.shared_probe_pid)
  }

  await cleanupSharedProbeWorkers(state.server)
  await stopProcessTree(state.pid)
  removeDaemonState()
}

async function daemonStatus(args: string[]) {
  let options = parseArgs(args)
  let state = readDaemonState()
  let server = options.server || state?.server || process.env.SKILLTRACE_SERVER || DEFAULT_SERVER
  let status = await getDaemonStatus(server)

  printDaemonStatus(status)
}

function daemonLogs(args: string[]) {
  let options = parseArgs(args)
  let lines = options.lines || 80
  let logPath = readDaemonState()?.log_path || DAEMON_LOG_PATH

  if (!fs.existsSync(logPath)) {
    console.log(`No SkillTrace daemon log found at ${logPath}`)
    return
  }

  let content = fs.readFileSync(logPath, 'utf8')
  let tail = content.split('\n').slice(-lines).join('\n')
  if (tail.trim()) console.log(tail)
}

function defaultTargetRoot() {
  return (
    process.env.SKILLTRACE_TARGET_ROOT ||
    process.env.INIT_CWD ||
    process.env.PWD ||
    process.cwd()
  )
}

function assertTraceTarget(
  targetRoot: string,
  profile: InstructionProfile,
  report: InstructionSurfaceReport,
) {
  if (instructionProfileReady(profile, report)) {
    return
  }

  console.error('The current directory does not look like a SkillTrace target repo.')
  console.error(`  directory: ${targetRoot}`)
  console.error(`  profile: ${profile}`)
  console.error(`  expected: ${instructionProfileExpectation(profile)}`)
  console.error('')
  console.error('Run skilltrace start from the target repo, or pass --target <repo>.')
  process.exit(1)
}

function unique<T>(values: T[]) {
  return [...new Set(values)]
}

function parseArgs(args: string[]) {
  let options: Options = {}

  for (let index = 0; index < args.length; index += 1) {
    let arg = args[index]

    if (arg === '--target') {
      options.target = args[++index]
    } else if (arg === '--server') {
      options.server = args[++index]
    } else if (arg === '--debug-probe') {
      options.debugProbe = true
    } else if (arg === '--note' || arg === '-n') {
      options.note = args[++index]
    } else if (arg === '--inject-instructions') {
      options.injectInstructions = true
    } else if (arg === '--no-inject-instructions') {
      options.injectInstructions = false
    } else if (arg === '--discard') {
      options.discard = true
    } else if (arg === '--yes' || arg === '-y') {
      options.yes = true
    } else if (arg === '--mode') {
      options.mode = parseTraceMode(args[++index])
    } else if (arg === '--instruction-profile') {
      options.instructionProfile = parseInstructionProfile(args[++index])
    } else if (arg === '--shared-probe') {
      options.sharedProbe = true
    } else if (arg === '--no-shared-probe') {
      options.sharedProbe = false
    } else if (arg === '--lines') {
      options.lines = Number(args[++index])
    } else if (arg === '--verbose') {
      options.verbose = true
    } else if (arg === '--agent') {
      options.agent = args[++index]
    } else {
      usage(`Unknown option: ${arg}`)
    }
  }

  return options
}

async function confirmDiscard(session: any) {
  if (!process.stdin.isTTY) {
    console.error('Refusing to discard without confirmation in a non-interactive terminal.')
    console.error('Run `skilltrace stop --discard --yes` to discard without prompting.')
    return false
  }

  console.log('Discard the active SkillTrace session?')
  console.log(`  run: ${session.run_id}`)
  console.log(`  repo: ${session.target_root}`)
  console.log('This will clean up instruction injection and delete the run record.')

  let reader = createInterface({
    input: process.stdin,
    output: process.stdout,
  })
  let answer = await reader.question('Discard this run? [y/N] ')
  reader.close()

  return answer.trim().toLowerCase() === 'y'
}

async function getJson(server: string, pathname: string) {
  return await requestJson(server, pathname, { commandName: commandName() })
}

async function postJson(server: string, pathname: string, body: any) {
  return await sendJson(server, pathname, body, { commandName: commandName() })
}

async function postSessionEvent(
  server: string,
  runId: string,
  eventType: string,
  payload: Record<string, unknown>,
) {
  try {
    await postJson(server, '/api/sessions/event', {
      run_id: runId,
      event_type: eventType,
      payload,
    })
  } catch (error) {
    let message = error instanceof Error ? error.message : String(error)
    console.warn(`Warning: failed to record ${eventType}: ${message}`)
  }
}

function commandName() {
  return DEV_MODE ? 'skilltrace-dev' : 'skilltrace'
}

async function getDaemonStatus(server: string) {
  let state = readDaemonState()
  let health = await getHealth(server)

  return {
    state,
    server,
    alive: health?.ok === true,
    health,
    pid_status: state?.pid ? probeStatus(state.pid) : 'unknown',
  }
}

async function getHealth(server: string) {
  try {
    return await getJson(server, '/api/health')
  } catch {
    return null
  }
}

async function isServerAlive(server: string) {
  return (await getHealth(server))?.ok === true
}

async function endServerSession(server: string) {
  try {
    await postJson(server, '/api/sessions/end', {})
  } catch {}
}

async function cleanupActiveInjection(server: string) {
  let active
  try {
    active = await getJson(server, '/api/sessions/status')
  } catch {
    return
  }

  if (!active.session) return

  let injection = ejectInstructions(active.session.target_root, active.session.run_id)
  if (!injection) return

  printInjectionResult('Instruction injection cleanup', injection)
  await postSessionEvent(server, active.session.run_id, 'instruction_injection_finished', {
    ...injection,
    target_root: active.session.target_root,
  })
}

function cleanupTargetInjection(targetRoot: string) {
  let injection = ejectExistingInstructions(targetRoot)
  if (!injection) return

  printInjectionResult('Previous instruction injection cleanup', injection)
}

async function waitForDaemon(pid: number, server: string) {
  for (let attempt = 0; attempt < 30; attempt += 1) {
    let health = await getHealth(server)
    if (health?.ok === true && processOwnsServer(pid, health.pid)) {
      return {
        ready: true,
        health,
      }
    }
    await sleep(500)
  }

  return {
    ready: false,
    health: await getHealth(server),
  }
}

async function waitForProbeStartup(pid: number) {
  await sleep(750)
  return processAlive(pid)
}

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms))
}

function printSession(label: string, server: string, session: any) {
  console.log(label)
  console.log(`  run: ${session.run_id}`)
  console.log(`  repo: ${session.target_root}`)
  if (session.trace_mode) {
    console.log(`  mode: ${session.trace_mode}`)
  }
  if (session.note) {
    console.log(`  note: ${session.note}`)
  }
  console.log(`  instruction injection: ${instructionInjectionStatus(session.target_root)}`)
  let probeLabel = session.probe_kind === 'shared' ? 'shared probe' : 'probe'
  console.log(`  ${probeLabel}: ${probeStatus(session.probe_pid)}`)
  if (session.probe_log_path) {
    console.log(`  probe log: ${session.probe_log_path}`)
  }
  console.log(`  ui: ${new URL(`/app/runs/${session.run_id}`, server)}`)
}

function printDiscardedSession(session: any) {
  console.log('Discarded SkillTrace session.')
  console.log(`  run: ${session.run_id}`)
  console.log(`  repo: ${session.target_root}`)
  console.log('  run record: deleted')
}

function printActiveSessionRefusal(server: string, session: any) {
  console.error('A SkillTrace session is already active.')
  console.error(`  run: ${session.run_id}`)
  console.error(`  repo: ${session.target_root}`)
  console.error(`  instruction injection: ${instructionInjectionStatus(session.target_root)}`)
  console.error(`  ui: ${new URL(`/app/runs/${session.run_id}`, server)}`)
  console.error('')
  console.error('Run `skilltrace stop` before starting another session.')
}

function printDaemonStatus(status: any) {
  if (status.alive && status.state && processAlive(status.state.pid)) {
    console.log('SkillTrace daemon is healthy.')
  } else if (status.alive) {
    console.log('SkillTrace server is healthy.')
  } else {
    console.log('SkillTrace daemon is not responding.')
  }

  console.log(`  server: ${status.server}`)
  if (status.state) {
    console.log(`  pid: ${status.pid_status}`)
    if (status.state.bind_host) {
      console.log(`  bind: ${status.state.bind_host}:${status.state.bind_port ?? '?'}`)
    }
    printDisplayUrls(status.state.ui_urls)
    printSharedProbeDaemonState(status.state)
    console.log(`  started: ${status.state.started_at}`)
    console.log(`  log: ${status.state.log_path}`)
  } else {
    console.log('  pid: no daemon state')
    console.log(`  log: ${DAEMON_LOG_PATH}`)
  }

  if (status.health?.session) {
    printSession('Active SkillTrace session', status.server, status.health.session)
  }
}

function printDiagnosticsCompact(data: any) {
  let status = diagnosticsStatus(data)
  console.log(`SkillTrace diagnostics: ${status}`)
  console.log(`  daemon: ${diagnosticsDaemonLabel(data)}`)
  console.log(`  server: ${data.server}`)

  if (data.session) {
    console.log(`  active session: running ${data.session.target_root}`)
  } else {
    console.log('  active session: none')
  }

  if (diagnosticsShowsSharedProbe(data)) {
    console.log(`  shared probe: ${data.checks.shared_probe.label}`)
  }

  console.log('  MCP:')
  for (let client of data.mcp.clients) {
    console.log(`    ${client.key}: ${diagnosticsMcpLabel(client)}`)
  }
}

function printDiagnosticsVerbose(data: any) {
  printDiagnosticsCompact(data)
  console.log('')
  console.log('Daemon')
  if (data.daemon) {
    console.log(`  pid: ${data.daemon.pid} ${data.checks.daemon_pid}`)
    console.log(`  server: ${data.daemon.server}`)
    console.log(
      `  bind: ${data.daemon.bind_host ?? '?'}:${data.daemon.bind_port ?? '?'}`,
    )
    for (let url of data.daemon.ui_urls ?? []) {
      console.log(`  ui: ${url}`)
    }
    console.log(`  started: ${data.daemon.started_at}`)
    console.log(`  log: ${data.daemon.log_path}`)
  } else {
    console.log('  state: missing')
  }

  console.log('')
  console.log('Server Process')
  console.log(`  pid: ${data.process.pid}`)
  console.log(`  mode: ${data.process.mode}`)
  console.log(`  host: ${data.process.host}`)
  console.log(`  port: ${data.process.port}`)
  console.log(`  platform: ${data.process.platform}`)
  console.log(`  node: ${data.process.node}`)

  if (diagnosticsShowsSharedProbe(data)) {
    console.log('')
    console.log('Shared Probe')
    console.log(`  status: ${data.checks.shared_probe.label}`)
    console.log(
      `  pid: ${data.daemon?.shared_probe_pid ?? 'missing'} ${data.checks.shared_probe_pid}`,
    )
    console.log(`  log: ${data.daemon?.shared_probe_log_path ?? 'none'}`)
    console.log(`  warning: ${data.daemon?.shared_probe_warning ?? 'none'}`)
  }

  console.log('')
  console.log('MCP')
  for (let client of data.mcp.clients) {
    console.log(`  ${client.key}: ${diagnosticsMcpLabel(client)}`)
    console.log(`    name: ${client.name}`)
    console.log(`    message: ${client.message}`)
    console.log(`    check: ${client.check_command}`)
    console.log(`    expected: ${client.expected_command} ${client.expected_args}`)
    console.log(`    command: ${client.command ?? 'unknown'}`)
    console.log(`    args: ${client.args ?? 'unknown'}`)
  }
}

function diagnosticsStatus(data: any) {
  let warning =
    data.checks.daemon_pid !== 'running' ||
    !data.checks.state_matches_server ||
    data.mcp.summary.tone === 'warning' ||
    (diagnosticsShowsSharedProbe(data) &&
      data.checks.shared_probe.tone === 'warning')

  return warning ? 'warning' : 'ok'
}

function diagnosticsDaemonLabel(data: any) {
  if (!data.daemon) return 'missing'
  return data.checks.daemon_pid
}

function diagnosticsShowsSharedProbe(data: any) {
  return (
    data.process.platform === 'darwin' ||
    !!data.daemon?.shared_probe_requested ||
    !!data.daemon?.shared_probe_pid ||
    !!data.daemon?.shared_probe_warning
  )
}

function diagnosticsMcpLabel(client: any) {
  if (client.status === 'missing') return 'not installed'
  if (client.status === 'timeout') return 'timeout'
  return client.status
}

function mcpUsage() {
  console.log('Usage: skilltrace mcp <serve|install|status|uninstall>')
  console.log('')
  console.log('Commands:')
  console.log('  serve      Start the stdio MCP server for agent clients')
  console.log('  install    Register SkillTrace MCP with supported agent clients')
  console.log('  status     Check SkillTrace MCP registration')
  console.log('  uninstall  Remove SkillTrace MCP registration')
  console.log('')
  console.log('Options:')
  console.log('  --agent codex|claude|gemini')
  console.log('  --verbose')
}

function printBindChangeHint(state: DaemonState, bindHost: string, port: string) {
  if (state.bind_host === bindHost && state.bind_port === port) return

  console.log(
    `SkillTrace daemon is already running with bind ${state.bind_host ?? 'unknown'}:${state.bind_port ?? '?'}.`,
  )
  console.log('Run `skilltrace daemon stop` before changing HOST or PORT.')
}

function printSharedProbeChangeHint(state: DaemonState, requested: boolean) {
  if (state.shared_probe_requested === requested) return

  let current = state.shared_probe_requested ? 'with' : 'without'
  let next = requested ? 'with' : 'without'
  console.log(`SkillTrace daemon is already running ${current} a shared probe.`)
  console.log(`Run \`skilltrace daemon stop\` before restarting ${next} a shared probe.`)
}

function printSharedProbeDaemonState(state: DaemonState) {
  if (!state.shared_probe_requested) return

  if (state.shared_probe_warning) {
    console.log(`  shared probe: unavailable (${state.shared_probe_warning})`)
    return
  }

  console.log(`  shared probe: ${probeStatus(state.shared_probe_pid)}`)
  if (state.shared_probe_log_path) {
    console.log(`  shared probe log: ${state.shared_probe_log_path}`)
  }
}

function printSharedProbeFallbackWarning(sharedProbe: SharedProbeStatus) {
  if (!sharedProbe.requested) return
  console.warn(`Warning: shared probe unavailable; using per-run probe. ${sharedProbe.reason}`)
}

function runScript(scriptPath: string, args: string[] = []) {
  let result = spawnSync(process.execPath, [
    ...nodeScriptArgs(scriptPath),
    ...args,
  ], {
    stdio: 'inherit',
    env: process.env,
  })

  process.exit(result.status ?? 1)
}

function runServe() {
  if (DEV_MODE) {
    let result = spawnSync('pnpm', ['dev'], {
      cwd: PROJECT_ROOT,
      stdio: 'inherit',
      env: process.env,
    })

    process.exit(result.status ?? 1)
  }

  let result = spawnSync(process.execPath, packagedServeArgs(), {
    cwd: PROJECT_ROOT,
    stdio: 'inherit',
    env: process.env,
  })

  process.exit(result.status ?? 1)
}

function serveCommand() {
  if (DEV_MODE) return 'pnpm'
  return process.execPath
}

function serveArgs() {
  if (DEV_MODE) return ['dev']
  return packagedServeArgs()
}

function packagedServeArgs() {
  return [
    '--import',
    RUNTIME_ENV_IMPORT_PATH,
    ...nodeScriptArgs('scripts/traceskill-serve.js'),
  ]
}

function nodeScriptArgs(scriptPath: string) {
  let builtPath = builtScriptPath(scriptPath)
  if (DIST_MODE) return [builtPath]

  return [
    '--import',
    TSX_LOADER_PATH,
    path.join(PROJECT_ROOT, scriptPath),
  ]
}

function builtScriptPath(scriptPath: string) {
  let parsed = path.parse(scriptPath)
  return path.join(ENTRY_DIR, `${parsed.name}.js`)
}

function probeStatus(pid?: number) {
  if (!pid) return 'not running'

  if (processAlive(pid)) return `${pid} running`
  return `${pid} not running`
}

function startProbeWorker(options: ProbeWorkerOptions) {
  let logPath = path.join(
    DAEMON_DIR,
    'logs/probes',
    `traceskill-probe-${options.runId}.log`,
  )
  fs.mkdirSync(path.dirname(logPath), { recursive: true })
  let logFd = fs.openSync(logPath, 'a')
  let args = [
    ...nodeScriptArgs('scripts/traceskill-probe-worker.ts'),
    '--run',
    options.runId,
    '--target',
    options.targetRoot,
    '--server',
    options.server,
  ]
  if (options.debug) args.push('--debug')

  let child = spawn(
    process.execPath,
    args,
    {
      detached: false,
      stdio: ['ignore', logFd, logFd],
      env: process.env,
    },
  )

  child.unref()
  fs.closeSync(logFd)

  if (typeof child.pid !== 'number') {
    throw new Error('Failed to start SkillTrace probe worker')
  }

  return {
    pid: child.pid,
    logPath,
  }
}

function startSharedProbeWorker(options: SharedProbeWorkerOptions) {
  let logPath = path.join(
    DAEMON_DIR,
    'logs/probes',
    'traceskill-probe-shared.log',
  )
  fs.mkdirSync(path.dirname(logPath), { recursive: true })
  let logFd = fs.openSync(logPath, 'a')
  let args = [
    ...nodeScriptArgs('scripts/traceskill-probe-worker.ts'),
    '--shared',
    '--server',
    options.server,
  ]
  if (options.debug) args.push('--debug')

  let child = spawn(
    process.execPath,
    args,
    {
      detached: false,
      stdio: ['ignore', logFd, logFd],
      env: process.env,
    },
  )

  child.unref()
  fs.closeSync(logFd)

  if (typeof child.pid !== 'number') {
    throw new Error('Failed to start SkillTrace shared probe worker')
  }

  return {
    pid: child.pid,
    logPath,
  }
}

function printInjectionResult(label: string, result: any) {
  console.log(label)
  console.log(`  status: ${result.status}`)
  console.log(`  instruction file: ${result.instruction_path ?? result.agents_path}`)
  console.log(`  instrumentation: ${result.instrumentation_path}`)
  if ('inserted_agents_instruction' in result) {
    console.log(`  inserted instruction: ${result.inserted_agents_instruction ? 'yes' : 'no'}`)
  }
  if ('created_instrumentation' in result) {
    console.log(`  created instrumentation: ${result.created_instrumentation ? 'yes' : 'no'}`)
  }
  if ('removed_agents_instruction' in result) {
    console.log(`  removed instruction: ${result.removed_agents_instruction ? 'yes' : 'no'}`)
  }
  if ('removed_instrumentation' in result) {
    console.log(`  removed instrumentation: ${result.removed_instrumentation ? 'yes' : 'no'}`)
  }
  for (let warning of result.warnings ?? []) {
    console.warn(`  warning: ${warning}`)
  }
}

function printInstrumentationWarning(instrumentation: any, injectRequested?: boolean) {
  if (instrumentation.status === 'ready') return
  if (injectRequested) return

  console.warn('Warning: SkillTrace instrumentation is not configured.')
  console.warn('Semantic MCP events are unlikely.')
  console.warn(
    'Run `skilltrace start --mode full` to let SkillTrace configure temporary tracing instructions.',
  )
  for (let warning of instrumentation.warnings ?? []) {
    console.warn(`  warning: ${warning}`)
  }
}

function passiveProbeSupport() {
  if (process.platform === 'darwin') {
    return {
      supported: true,
      platform: process.platform,
    }
  }

  if (process.platform === 'linux') {
    if (commandExists('inotifywait')) {
      return {
        supported: true,
        platform: process.platform,
      }
    }

    return {
      supported: false,
      platform: process.platform,
      reason: 'Passive file probing on linux requires inotifywait. Install inotify-tools to enable passive tracing.',
    }
  }

  return {
    supported: false,
    platform: process.platform,
    reason: `Passive file probing is not available on ${process.platform} yet; semantic tracing will still run.`,
  }
}

function runExecutionEnvironment(
  probe: PassiveProbeSupport,
  sharedProbe: SharedProbeStatus,
) {
  return {
    skilltrace_version: skilltraceVersion(),
    skilltrace_mode: DEV_MODE ? 'dev' : 'package',
    skilltrace_command: expectedMcpServerCommand(),
    platform: process.platform,
    arch: process.arch,
    os_release: os.release(),
    node: process.version,
    probe_backend: passiveProbeBackend(probe),
    probe_mode: sharedProbe.available
      ? 'shared'
      : probe.supported
        ? 'run'
        : 'unavailable',
  }
}

function skilltraceVersion() {
  try {
    let content = fs.readFileSync(PACKAGE_JSON_PATH, 'utf8')
    let json = JSON.parse(content)
    return typeof json.version === 'string' ? json.version : 'unknown'
  } catch {
    return 'unknown'
  }
}

function passiveProbeBackend(probe: PassiveProbeSupport) {
  if (!probe.supported) return 'unavailable'
  if (probe.platform === 'darwin') return 'fs_usage'
  if (probe.platform === 'linux') return 'inotifywait'
  return 'unknown'
}

function sharedProbeRequested(options: Options) {
  if (typeof options.sharedProbe === 'boolean') return options.sharedProbe
  return process.platform === 'darwin'
}

async function prepareSharedProbe(
  requested: boolean,
  server: string,
): Promise<PreparedSharedProbe> {
  if (!requested) {
    return {
      requested: false,
    }
  }

  let sharedWorkers = sharedProbeWorkers()
  let foreignWorker = sharedWorkers.find((worker) =>
    worker.server && worker.server !== server
  )
  if (foreignWorker) {
    return {
      requested: true,
      warning: `another shared probe is already running for ${foreignWorker.server ?? 'an unknown server'}`,
      blocksRunProbe: true,
    }
  }

  let staleWorkers = sharedWorkers.filter((worker) =>
    worker.server === server || !worker.server
  )
  if (staleWorkers.length > 0) {
    for (let worker of staleWorkers) {
      await stopProcessTree(worker.pid)
    }
  }

  let existing = readDaemonState()
  if (
    existing?.shared_probe_pid &&
    existing.server !== server &&
    processAlive(existing.shared_probe_pid)
  ) {
    return {
      requested: true,
      warning: `another shared probe is already running for ${existing.server}`,
      blocksRunProbe: true,
    }
  }

  if (process.platform !== 'darwin') {
    return {
      requested: true,
      warning: 'shared probe is macOS-only; this platform uses per-run probing',
    }
  }

  if (!commandExists('fs_usage')) {
    return {
      requested: true,
      warning: 'fs_usage was not found on PATH',
    }
  }

  primeSudo()

  return {
    requested: true,
  }
}

function sharedProbeStatus(server: string): SharedProbeStatus {
  let state = readDaemonState()
  if (!state?.shared_probe_requested) {
    return {
      requested: false,
      available: false,
    }
  }

  if (state.server !== server) {
    return {
      requested: true,
      available: false,
      state,
      reason: `daemon shared probe belongs to ${state.server}`,
    }
  }

  if (state.shared_probe_warning) {
    return {
      requested: true,
      available: false,
      state,
      reason: state.shared_probe_warning,
      blocksRunProbe: state.shared_probe_blocks_run_probe,
    }
  }

  if (state.shared_probe_pid && processAlive(state.shared_probe_pid)) {
    return {
      requested: true,
      available: true,
      state,
    }
  }

  return {
    requested: true,
    available: false,
    state,
    reason: 'shared probe process is not running',
  }
}

function withPassiveProbeWarning(instrumentation: any, probe: PassiveProbeSupport) {
  if (probe.supported) return instrumentation

  return {
    ...instrumentation,
    warnings: [...(instrumentation.warnings ?? []), probe.reason],
  }
}

function printPassiveProbeWarning(probe: PassiveProbeSupport) {
  if (probe.supported) return
  console.warn(`Warning: ${probe.reason}`)
}

function printProbeUnavailableWarning(reason?: string) {
  console.warn(`Warning: ${reason ?? 'passive probe is unavailable'}`)
}

function traceModeForStart(options: Options): TraceMode {
  if (options.mode) return options.mode
  if (options.injectInstructions === false) return 'passive_only'
  return 'full'
}

function parseTraceMode(value?: string): TraceMode {
  if (
    value === 'full' ||
    value === 'passive_reflection' ||
    value === 'passive_only'
  ) {
    return value
  }

  usage(`Unknown trace mode: ${value ?? ''}`)
}

function parseInstructionProfile(value?: string): InstructionProfileOption {
  if (
    value === 'auto' ||
    value === 'agents' ||
    value === 'claude_code'
  ) {
    return value
  }
  if (value === 'claude-code') return 'claude_code'

  usage(`Unknown instruction profile: ${value ?? ''}`)
}

function commandExists(command: string) {
  return spawnSync('which', [command], { stdio: 'pipe' }).status === 0
}

function primeSudo() {
  let sudo = spawnSync('sudo', ['-v'], { stdio: 'inherit' })
  if (sudo.status !== 0) {
    throw new Error('sudo authorization failed')
  }
}

function displayUrls(host: string, port: string) {
  if (host === '0.0.0.0' || host === '::') {
    let urls = networkAddresses().map((address) => `http://${address}:${port}`)
    return urls.length > 0 ? [...new Set(urls)] : [`http://127.0.0.1:${port}`]
  }

  return [`http://${host || '127.0.0.1'}:${port}`]
}

function networkAddresses() {
  let addresses: string[] = []

  for (let values of Object.values(os.networkInterfaces())) {
    for (let value of values ?? []) {
      if (value.family !== 'IPv4' || value.internal) continue
      addresses.push(value.address)
    }
  }

  return addresses
}

function printDisplayUrls(urls?: string[]) {
  for (let url of urls ?? []) {
    console.log(`  ui: ${url}`)
  }
}

function usage(message: string): never {
  console.error(message)
  console.error('Usage: skilltrace [--version] <serve|start|status|diagnostics|end|stop|mcp>')
  console.error('       skilltrace start [--target <repo>] [--server <url>] [--mode full|passive_reflection|passive_only] [--instruction-profile auto|agents|claude-code] [--note <text>]')
  console.error('       skilltrace stop [--discard] [--yes]')
  console.error('       skilltrace diagnostics [--verbose]')
  console.error('       skilltrace mcp <serve|install|status|uninstall> [--agent codex|claude|gemini] [--verbose]')
  console.error('       skilltrace daemon <start|status|stop|logs> [--shared-probe|--no-shared-probe]')
  process.exit(1)
}

await main().catch(handleFatalError)

function handleFatalError(error: unknown): never {
  if (process.env.SKILLTRACE_DEBUG_STACK && error instanceof Error && error.stack) {
    console.error(error.stack)
  } else if (error instanceof Error) {
    console.error(error.message)
  } else {
    console.error(String(error))
  }

  process.exit(1)
}

type Options = {
  target?: string
  server?: string
  debugProbe?: boolean
  discard?: boolean
  yes?: boolean
  injectInstructions?: boolean
  mode?: TraceMode
  instructionProfile?: InstructionProfileOption
  sharedProbe?: boolean
  lines?: number
  note?: string
  verbose?: boolean
  agent?: string
}

type TraceMode = 'full' | 'passive_reflection' | 'passive_only'

type ProbeWorkerOptions = {
  runId: string
  targetRoot: string
  server: string
  debug?: boolean
}

type ProbeWorker = {
  pid: number
  logPath: string
}

type SharedProbeWorkerOptions = {
  server: string
  debug?: boolean
}

type PassiveProbeSupport = {
  supported: boolean
  platform: NodeJS.Platform
  reason?: string
}

type PreparedSharedProbe = {
  requested: boolean
  warning?: string
  blocksRunProbe?: boolean
  worker?: {
    pid: number
    logPath: string
  }
}

type SharedProbeStatus = {
  requested: boolean
  available: boolean
  state?: DaemonState
  reason?: string
  blocksRunProbe?: boolean
}
